name: Postman Collection Run
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  postman:
    runs-on: ubuntu-latest
    name: Run Payments Tests
    steps:
      - uses: actions/checkout@v4

      - name: Install and Run Postman Tests
        env:
          POSTMAN_API_KEY: ${{ secrets.POSTMAN_API_KEY }}
        run: |
          curl -o- "https://dl-cli.pstmn.io/install.sh" | sh
          export PATH="$HOME/.local/share/postman-cli:$PATH"
          postman login --with-api-key "$POSTMAN_API_KEY"
          postman collection run "52238111-6bd7c512-ea9e-47f4-a7b5-3d07b2991903" \
            --environment "52238111-310fba8f-85e9-4e9d-8e37-8cfa71f59680" \
            --verbose